### ISSUE TITLE
Vælg tilladelse og send til bruger (Support)

### ISSUE THREAD

**Issue by Minerr** [Minerr/GettingReal#15]
Som en supportmedarbejder vil jeg gerne vælge en tilladelse, definere tid på den, og sende den til brugeren jeg hjælper.

**Comment by LathenHD** [comment]
Opret UI Layer

**Comment by LathenHD** [comment]
UI der viser liste af alle tilladelser.

**Comment by Minerr** [comment]
Menu funktionalitet: "Send tilladelse til accept". 
 - Vælg en tilladelse, angiv udløbstid og angiv bruger id
 - Gem tilladelsen til en fil på computer
