### ISSUE TITLE
Se aktive samtykker (Bruger)

### ISSUE THREAD

**Issue by Benj8147** [Minerr/GettingReal#17]
Som en bruger vil jeg gerne kunne se alle mine aktive samtykker og deres udløbstider, så jeg ved jeg ikke bliver udnyttet.

**Comment by Minerr** [comment]
Menu funktionalitet: "Vis liste af aktive samtykker"
 - Se alle aktive samtykker ud fra bruger id
- Se udløbs tider på samtykkerne.
